package-lock.json
package.json
src/App.js

Se agregan las siguentes rutas:
{location !== "/login" && (<Route path='/' />)}
<Route exact path='/login'/>
<Route exact path='/dashboard'/>
<Route exact path='/create_menu'/>
<Route exact path='/create_recipe'/>
<Route exact path='/register' />
<Route exact path='/create_ingredients' />
<Route exact path='/profile' />
<Route exact path='/store' />
<Route exact path='/orders' />

Agregar rutas frontEnd sin componentes aún

---

src/Pages/CreateIngredient/CreateIngredient.jsx
src/Pages/RegisterPage/RegisterPage.jsx
src/Shared/NavBar/NavBar.jsx
src/Shared/NavBar/NavBar.module.css
src/pages/createItemMenu/CreateItemMenu.jsx

Se creó el componente navBar y se implementó provisionalmente en algunas páginas

Creando el NavBar e implementándolo

---

src/components/CreateEditStore/CreateEditStore.module.css
src/components/CreateIngredient/CreateIngredient.module.css
src/components/Register/Register.module.css
src/components/createItemMenu/form.module.css

se cambia el valor start por flex-start como lo pedía el warning

eliminando warnigs css

---

package-lock.json
package.json
src/components/createItemMenu/Form.jsx
src/components/createItemMenu/form.module.css
src/pages/createItemMenu/CreateItemMenu.jsx

Aún no se ha definido como mostrar los mensajes de errores, de resto todo está listo
PreviewÑ

Feature/Form Control on Create Item Menu Page

---

src/App.js
src/redux/Actions/actions.js
src/redux/Actions/types.js
src/redux/Reducer/reducer.js

Se agrego estado redux menu y la action get_menu

---

src/Pages/RegisterPage/RegisterPage.jsx
src/Shared/NavBar/NavBar.module.css
src/components/CreateEditStore/CreateEditStore.jsx
src/components/Register/Register.jsx
src/components/Register/Register.module.css
src/redux/Actions/actions.js

a parte de las actions también se agregó un Formik al componente "Register" y una pequeña validación con Yup

se crearon las actions "createUser" y "deleteIngredient" 

---

src/Pages/Menu/Menu.jsx
src/Shared/Pagination/Pagination.jsx
src/Shared/Pagination/Pagination.module.css
src/components/MenuCards/MenuCards.jsx

Se implementó por completo la lógica y renderización (pendiente de diseño real) el componente pagination y Menu_cards

Actualizando Paginado e implementandolo

---

src/components/Register/Register.module.css

Agregando espacio al componente de crear menus

---

src/Pages/RegisterPage/RegisterPage.jsx
src/components/Register/Register.jsx
src/components/Register/Register.module.css

valida: "phone", "password", "email", "account_name" 
también corregí los nombres de las propiedades del objeto "initialValues"

corrige validaciones de formulario de "register"

---

src/redux/Reducer/reducer.js

Habia un error en el reducer con el nombre del estado menus, por esa razon no renderizaba las tarjetas, corregido

Corrigiendo error en el reducer

---

src/Shared/NavBar/NavBar.jsx

Se actualizó navBar según lo requerido

actualizando navbar

---

src/App.js
src/Pages/Ingredients/Ingredients.jsx
src/Pages/Ingredients/Ingredients.module.css
src/Shared/NavBar/NavBar.jsx
src/components/Card_Ingredient/Card_Ingredient.jsx
src/components/Card_Ingredient/Card_Ingredients.module.css
src/components/IngredientsCards/IngredientsCards.jsx
src/components/IngredientsCards/IngredientsCards.module.css

Se crean los componentes que renderizan los ingredientes

crear componentes de ingredientes

---

src/Pages/EditStore/EditSore.jsx
src/Pages/EditStore/EditStore.module.css
src/Pages/Ingredients/Ingredients.jsx
src/Pages/Ingredients/Ingredients.module.css
src/Pages/Menu/Menu.jsx
src/Pages/Menu/Menu.module.css
src/Pages/RegisterPage/RegisterPage.jsx
src/Pages/RegisterPage/Registerpage.module.css
src/Shared/NavBar/NavBar.module.css
src/components/CreateIngredient/CreateIngredient.module.css

Se fijó el navbar en todas las páginas del momento

Posicionando naBar FIX

---

src/Pages/Recipe/Create/RecipeCreate.jsx
src/components/Recipe/Create/CreateRecipe.css
src/components/Recipe/Create/CreateRecipe.js

agregando CreateRecipe

---

src/Pages/Menu/Menu.jsx
src/redux/Actions/actions.js

Habian conflictos con el ultimo pull y no funcionaba la app.

solucionando conflictos en el merge

---

package-lock.json
package.json
src/App.js

implementacion socket.io-client

---

.eslintrc.js
src/Pages/EditStore/EditSore.jsx
src/Pages/Menu/Menu.module.css
src/Pages/Menu/menu.module.css
src/Pages/RegisterPage/RegisterPage.jsx
src/Shared/NavBar/NavBar.jsx
src/Shared/NavBar/NavBar.module.css
src/components/CreateEditStore/CreateEditStore.jsx
src/components/CreateIngredient/CreateIngredient.jsx
src/components/UpdateIngredients/UpdateIngredients.jsx

Se corrigen algunos errores que marcaba la herramineta eslint que impedían el funcionamiento de la app

Corrigiendo errores de ESlint

---

src/Pages/Ingredients/Ingredients.module.css
src/components/Card_Ingredient/Card_Ingredient.jsx
src/components/Card_Ingredient/Card_Ingredients.module.css
src/components/CreateIngredient/CreateIngredient.jsx
src/components/CreateIngredient/CreateIngredient.module.css
src/components/IngredientsCards/IngredientsCards.jsx
src/components/IngredientsCards/IngredientsCards.module.css

se quita la prop "id" que se mostraba

arregla detalles de css en el componente "Ingredientes"

---

src/App.js
src/components/createItemMenu/Form.jsx
src/index.js

Se soluciono fallo en el formulario de actualizacion menu

---

src/Pages/RegisterPage/RegisterPage.jsx
src/components/Register/Register.jsx
src/components/Register/Register.module.css
src/redux/Actions/actions.js

Arreglos css en Registro

---

src/components/Register/Register.jsx
src/components/Register/Register.module.css
src/components/createItemMenu/Form.jsx
src/components/createItemMenu/form.module.css
src/redux/Actions/actions.js

pendiente cloudinary en createItemMenu

cambios en CreateItemMenu y ya anda cloudinary en register

---

src/Pages/Menu/CreateOrUpdate/CreateItemMenu.jsx
src/components/createItemMenu/Form.jsx

Se guarda el contenido del form en localStorage incluida la imagen y al momento de hacer submit se borra el localStorage. No se pisa con el componente actualizar menus.
PD: No esta funcionando "Crear Menu", pero si "actualizar" se usa el mismo formulario.

Form con local storage

---

.eslintrc.js
src/components/createItemMenu/Form.jsx

clean submite form

---

src/components/createItemMenu/Form.jsx

ahora si x2
